import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { ensureCliLink, selectCliBinDirectory } from "../dist/ensure-cli-link.js";

function fixture() {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), "pilink-cli-link-"));
  const bin = path.join(home, "bin");
  const cli = path.join(home, "PiLink", "dist", "cli.js");
  fs.mkdirSync(bin, { recursive: true });
  fs.mkdirSync(path.dirname(cli), { recursive: true });
  fs.writeFileSync(cli, "#!/usr/bin/env node\nconsole.log('fixture');\n", { mode: 0o600 });
  return { home, bin, cli };
}

test("source build exposes pilink through an existing user PATH directory", () => {
  const { home, bin, cli } = fixture();
  const messages = [];
  try {
    const result = ensureCliLink({
      cliTarget: cli,
      homeDirectory: home,
      pathValue: bin,
      platform: process.platform,
      env: {},
      info: (message) => messages.push(message),
      warn: (message) => messages.push(message),
    });
    assert.equal(result.status, "linked");
    assert.ok(result.linkPath);
    assert.match(messages.join("\n"), /CLI available as `pilink`/u);

    if (process.platform === "win32") {
      assert.equal(path.basename(result.linkPath), "pilink.cmd");
      assert.match(fs.readFileSync(result.linkPath, "utf8"), /Generated by PiLink source build/u);
    } else {
      assert.equal(fs.realpathSync(result.linkPath), fs.realpathSync(cli));
      assert.notEqual(fs.statSync(cli).mode & 0o111, 0);
    }
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("source build never overwrites an unrelated pilink command", () => {
  const { home, bin, cli } = fixture();
  const commandPath = path.join(bin, process.platform === "win32" ? "pilink.cmd" : "pilink");
  fs.writeFileSync(commandPath, "existing command\n");
  try {
    const result = ensureCliLink({
      cliTarget: cli,
      homeDirectory: home,
      pathValue: bin,
      platform: process.platform,
      env: {},
      info: () => {},
      warn: () => {},
    });
    assert.equal(result.status, "conflict");
    assert.equal(fs.readFileSync(commandPath, "utf8"), "existing command\n");
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("CLI linker refuses PATH directories outside the user's home", () => {
  const { home } = fixture();
  try {
    assert.equal(selectCliBinDirectory({
      pathValue: path.dirname(process.execPath),
      homeDirectory: home,
      nodeExecutable: process.execPath,
      platform: process.platform,
    }), undefined);
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("CLI linker rejects a home PATH symlink that escapes outside the home", { skip: process.platform === "win32" }, () => {
  const { home } = fixture();
  const outside = fs.mkdtempSync(path.join(os.tmpdir(), "pilink-cli-outside-"));
  const linkedBin = path.join(home, "linked-bin");
  fs.symlinkSync(outside, linkedBin, "dir");
  try {
    assert.equal(selectCliBinDirectory({
      pathValue: linkedBin,
      homeDirectory: home,
      nodeExecutable: process.execPath,
      platform: process.platform,
    }), undefined);
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
    fs.rmSync(outside, { recursive: true, force: true });
  }
});

test("CLI linker prefers a stable user bin over a version-specific Node bin", () => {
  const { home } = fixture();
  const localBin = path.join(home, ".local", "bin");
  const nodeBin = path.join(home, ".nvm", "versions", "node", "v24.18.0", "bin");
  fs.mkdirSync(localBin, { recursive: true });
  fs.mkdirSync(nodeBin, { recursive: true });
  try {
    assert.equal(selectCliBinDirectory({
      pathValue: [nodeBin, localBin].join(path.delimiter),
      homeDirectory: home,
      nodeExecutable: path.join(nodeBin, process.platform === "win32" ? "node.exe" : "node"),
      platform: process.platform,
    }), localBin);
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});

test("CI and explicit opt-out disable source-build linking", () => {
  const { home, bin, cli } = fixture();
  try {
    assert.equal(ensureCliLink({
      cliTarget: cli,
      homeDirectory: home,
      pathValue: bin,
      env: { CI: "true" },
      info: () => {},
      warn: () => {},
    }).status, "skipped");
    assert.equal(ensureCliLink({
      cliTarget: cli,
      homeDirectory: home,
      pathValue: bin,
      env: { PILINK_SKIP_CLI_LINK: "1" },
      info: () => {},
      warn: () => {},
    }).status, "skipped");
  } finally {
    fs.rmSync(home, { recursive: true, force: true });
  }
});
