import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import type { ConfigSnapshot } from "./configuration.js";
import { normalizeHostingSelection, type CloudflareAuthKind, type HostingSelection } from "./hosting-model.js";
import type { ProcessViewState } from "./protocol.js";

const MANAGED_CONFIG_HEADER = "# Managed by VSPiLink Cloudflare hosting. Do not add secrets here.";
const MANAGED_SYSTEMD_HEADER = "# Managed by VSPiLink hosting. Generated file; do not edit.";
const SERVER_UNIT = "vspilink-server.service";
const TUNNEL_UNIT = "vspilink-cloudflared.service";
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const TUNNEL_NAME = /^[A-Za-z0-9](?:[A-Za-z0-9_.-]{0,61}[A-Za-z0-9])?$/;

export interface ManagedNamedHostingEvidence {
  hosting: HostingSelection & { kind: "cloudflare-named" };
  zoneConfirmed: boolean;
  stateDirectory: string;
  systemdUserDirectory: string;
}

export interface ManagedUnitRuntimeState {
  serverState: string;
  tunnelState: string;
  enableState: string;
}

export interface NamedHostingRecoveryOptions {
  systemdUserDirectory: string;
  expectedUid?: number;
  preferredHosting?: HostingSelection;
}

export interface ManagedServerRestartOptions {
  systemctlPath: string;
  systemdUserDirectory: string;
  expectedUid?: number;
}

/**
 * Reconstruct only non-secret Named Tunnel metadata from files generated by
 * VSPiLink. Every adopted file is owner checked, non-symlinked and private;
 * arbitrary cloudflared/systemd files are deliberately rejected.
 */
export function inspectManagedNamedHosting(
  snapshot: ConfigSnapshot,
  options: NamedHostingRecoveryOptions,
): ManagedNamedHostingEvidence {
  if (snapshot.hostingMode !== "cloudflare-named") throw new Error("This configuration does not use a Cloudflare Named Tunnel.");
  const expectedUid = options.expectedUid ?? (typeof process.getuid === "function" ? process.getuid() : undefined);
  const configDirectory = path.dirname(path.resolve(snapshot.configPath));
  const stateDirectory = path.join(configDirectory, "cloudflare");
  const systemdUserDirectory = path.resolve(options.systemdUserDirectory);

  assertPrivateDirectory(configDirectory, expectedUid, "VSPiLink configuration directory");
  assertPrivateFile(snapshot.configPath, expectedUid, 1024 * 1024, "VSPiLink configuration");
  assertPrivateDirectory(stateDirectory, expectedUid, "managed Cloudflare directory");
  assertPrivateDirectory(systemdUserDirectory, expectedUid, "user systemd directory");

  const cloudflaredConfigPath = path.join(stateDirectory, "config.yml");
  const cloudflaredConfig = readPrivateTextFile(cloudflaredConfigPath, expectedUid, 64 * 1024, "cloudflared configuration");
  const parsed = parseManagedCloudflaredConfig(cloudflaredConfig);
  const expectedOrigin = `http://127.0.0.1:${snapshot.port}`;
  if (parsed.origin !== expectedOrigin) throw new Error("The managed tunnel origin does not match the configured VSPiLink port.");

  const serverUrl = strictHttpsOrigin(snapshot.serverUrl);
  const landingHostname = strictHostname(snapshot.values.PI_LANDING_HOSTNAME);
  if (parsed.mcpHostname !== new URL(serverUrl).hostname || parsed.landingHostname !== landingHostname) {
    throw new Error("The managed tunnel hostnames do not match the VSPiLink configuration.");
  }

  const preferred = normalizeHostingSelection(options.preferredHosting, true);
  const preferredMatches = preferred?.kind === "cloudflare-named" &&
    preferred.tunnelName === parsed.tunnelName && preferred.mcpHostname === parsed.mcpHostname &&
    preferred.landingHostname === parsed.landingHostname && preferred.cloudflareAuthKind === parsed.authKind &&
    (parsed.authKind !== "tunnel-token-file" || preferred.tunnelId === parsed.tunnelId);
  const zoneName = preferredMatches
    ? preferred.zoneName as string
    : suggestedZone(parsed.mcpHostname, parsed.landingHostname);

  const normalized = normalizeHostingSelection({
    kind: "cloudflare-named",
    tunnelName: parsed.tunnelName,
    zoneName,
    mcpHostname: parsed.mcpHostname,
    landingHostname: parsed.landingHostname,
    cloudflareAuthKind: parsed.authKind,
    ...(parsed.tunnelId ? { tunnelId: parsed.tunnelId } : {}),
    ...(preferredMatches && preferred.credentialReference ? { credentialReference: preferred.credentialReference } : {}),
    ...(preferredMatches && preferred.credentialLabel ? { credentialLabel: preferred.credentialLabel } : {}),
  }, true);
  if (!normalized || normalized.kind !== "cloudflare-named") throw new Error("The managed Named Tunnel metadata is invalid.");

  if (parsed.authKind === "origin-certificate") {
    const expectedCredentialsPath = path.join(stateDirectory, "tunnel-credentials.json");
    if (parsed.credentialsPath !== expectedCredentialsPath) {
      throw new Error("The managed tunnel uses a credential file outside the expected private directory.");
    }
    validateTunnelCredentials(expectedCredentialsPath, expectedUid);
  }

  validateManagedUnits({
    systemdUserDirectory,
    stateDirectory,
    configPath: snapshot.configPath,
    cloudflaredConfigPath,
    serverUrl,
    origin: expectedOrigin,
    tunnelName: parsed.tunnelName,
    authKind: parsed.authKind,
    tunnelId: parsed.tunnelId,
    expectedUid,
  });

  return {
    hosting: normalized as HostingSelection & { kind: "cloudflare-named" },
    zoneConfirmed: Boolean(preferredMatches),
    stateDirectory,
    systemdUserDirectory,
  };
}

export async function readManagedUnitRuntimeState(
  systemctlPath: string,
  runner: (executable: string, args: readonly string[]) => Promise<{ code: number | null; stdout: string }> = runStatusCommand,
): Promise<ManagedUnitRuntimeState> {
  const [server, tunnel, enabled] = await Promise.all([
    runner(systemctlPath, ["--user", "is-active", SERVER_UNIT]),
    runner(systemctlPath, ["--user", "is-active", TUNNEL_UNIT]),
    runner(systemctlPath, ["--user", "is-enabled", TUNNEL_UNIT]),
  ]);
  return {
    serverState: safeUnitState(server.stdout, server.code === 0 ? "active" : "inactive"),
    tunnelState: safeUnitState(tunnel.stdout, tunnel.code === 0 ? "active" : "inactive"),
    enableState: safeUnitState(enabled.stdout, enabled.code === 0 ? "enabled" : "unknown"),
  };
}

/**
 * Restart only the locally managed PiLink server unit. This deliberately does
 * not inspect, start, stop, or reload the Cloudflare tunnel and needs no
 * Cloudflare credential. The fixed unit is accepted only after its private,
 * generated definition is matched to the active PiLink configuration.
 */
export async function restartManagedServerUnit(
  snapshot: ConfigSnapshot,
  options: ManagedServerRestartOptions,
  runner: (executable: string, args: readonly string[]) => Promise<{ code: number | null; stdout: string }> = runManagedCommand,
): Promise<void> {
  validateManagedServerUnit(snapshot, options);
  const restarted = await runner(options.systemctlPath, ["--user", "restart", SERVER_UNIT]);
  if (restarted.code !== 0) throw new Error("systemd could not restart the VSPiLink server service.");
  const active = await runner(options.systemctlPath, ["--user", "is-active", SERVER_UNIT]);
  if (active.code !== 0 || safeUnitState(active.stdout, "inactive") !== "active") {
    throw new Error("The VSPiLink server service is not active after the restart.");
  }
}

/** Validate the fixed server unit without changing systemd state. */
export function validateManagedServerUnit(
  snapshot: ConfigSnapshot,
  options: ManagedServerRestartOptions,
): void {
  if (snapshot.hostingMode !== "cloudflare-named") throw new Error("This configuration does not use a Cloudflare Named Tunnel.");
  const expectedUid = options.expectedUid ?? (typeof process.getuid === "function" ? process.getuid() : undefined);
  const configDirectory = path.dirname(path.resolve(snapshot.configPath));
  const systemdUserDirectory = path.resolve(options.systemdUserDirectory);
  assertPrivateDirectory(configDirectory, expectedUid, "VSPiLink configuration directory");
  assertPrivateFile(snapshot.configPath, expectedUid, 1024 * 1024, "VSPiLink configuration");
  assertPrivateDirectory(systemdUserDirectory, expectedUid, "user systemd directory");

  const server = readPrivateTextFile(
    path.join(systemdUserDirectory, SERVER_UNIT),
    expectedUid,
    128 * 1024,
    "VSPiLink systemd unit",
  );
  if (!server.startsWith(`${MANAGED_SYSTEMD_HEADER}\n`)) {
    throw new Error("The existing server unit is not managed by VSPiLink.");
  }
  const lines = server.split("\n");
  const required = [
    `Environment=${JSON.stringify(`PILINK_CONFIG=${path.resolve(snapshot.configPath)}`)}`,
    `Environment=${JSON.stringify("HOST=127.0.0.1")}`,
    `Environment=${JSON.stringify(`PORT=${snapshot.port}`)}`,
    `Environment=${JSON.stringify(`SERVER_URL=${snapshot.serverUrl}`)}`,
  ];
  if (required.some((line) => !lines.includes(line))) {
    throw new Error("The managed server unit does not match the active private configuration.");
  }
  const execStart = lines.find((line) => line.startsWith("ExecStart="));
  if (!execStart || !execStart.endsWith(` ${JSON.stringify("serve")}`)) {
    throw new Error("The managed server unit does not start the expected VSPiLink runtime.");
  }
}

export function reconcileManagedProcessState(
  local: ProcessViewState,
  managed: { configured: boolean; serverState: string; tunnelState: string },
): ProcessViewState {
  if (["running", "starting", "stopping"].includes(local.status) || !managed.configured) return local;
  if (managed.serverState === "active") {
    return { status: "running", mode: "Cloudflare Named Tunnel · managed service", awaitingInput: false };
  }
  if ([managed.serverState, managed.tunnelState].some((value) => value === "activating" || value === "reloading")) {
    return { status: "starting", mode: "Cloudflare Named Tunnel · managed service", awaitingInput: false };
  }
  if ([managed.serverState, managed.tunnelState].some((value) => value === "failed")) {
    return { status: "error", mode: "Cloudflare Named Tunnel · managed service", awaitingInput: false };
  }
  return local;
}

export function managedMcpOrigin(value: unknown): string | undefined {
  if (typeof value !== "string" || value.length > 2_048) return undefined;
  try {
    const parsed = new URL(value);
    if (
      parsed.protocol !== "https:" || parsed.username || parsed.password || parsed.search || parsed.hash ||
      parsed.pathname !== "/sse"
    ) return undefined;
    return parsed.origin;
  } catch {
    return undefined;
  }
}

export function managedLandingOrigin(value: unknown): string | undefined {
  if (typeof value !== "string" || value.length > 2_048) return undefined;
  try {
    const parsed = new URL(value);
    if (
      parsed.protocol !== "https:" || parsed.username || parsed.password || parsed.search || parsed.hash ||
      (parsed.pathname !== "/" && parsed.pathname !== "")
    ) return undefined;
    return parsed.origin;
  } catch {
    return undefined;
  }
}

interface ParsedManagedConfig {
  tunnelName: string;
  authKind: CloudflareAuthKind;
  tunnelId?: string;
  credentialsPath?: string;
  mcpHostname: string;
  landingHostname: string;
  origin: string;
}

function parseManagedCloudflaredConfig(contents: string): ParsedManagedConfig {
  if (/\r|\0/.test(contents)) throw new Error("The managed cloudflared configuration contains invalid characters.");
  const lines = contents.replace(/\n$/, "").split("\n");
  let index = 0;
  const exact = (expected: string) => {
    if (lines[index++] !== expected) throw new Error("The cloudflared configuration does not match the VSPiLink-managed format.");
  };
  const scalar = (prefix: string): string => {
    const line = lines[index++];
    if (!line?.startsWith(prefix)) throw new Error("The cloudflared configuration does not match the VSPiLink-managed format.");
    try {
      const value = JSON.parse(line.slice(prefix.length));
      if (typeof value !== "string" || /[\r\n\0]/.test(value)) throw new Error();
      return value;
    } catch {
      throw new Error("The cloudflared configuration contains an invalid value.");
    }
  };
  exact(MANAGED_CONFIG_HEADER);
  const tunnelValue = scalar("tunnel: ");
  let credentialsPath: string | undefined;
  if (lines[index]?.startsWith("credentials-file: ")) credentialsPath = path.resolve(scalar("credentials-file: "));
  const metrics = scalar("metrics: ");
  if (!/^127\.0\.0\.1:[1-9][0-9]{0,4}$/.test(metrics) || Number(metrics.split(":")[1]) > 65_535) {
    throw new Error("The managed cloudflared metrics address is not safe.");
  }
  exact("loglevel: info");
  exact("ingress:");
  const mcpHostname = strictHostname(scalar("  - hostname: "));
  const firstOrigin = strictLoopbackOrigin(scalar("    service: "));
  exact("    originRequest:");
  exact("      connectTimeout: 10s");
  const landingHostname = strictHostname(scalar("  - hostname: "));
  const secondOrigin = strictLoopbackOrigin(scalar("    service: "));
  exact("    originRequest:");
  exact("      connectTimeout: 10s");
  exact("  - service: http_status:404");
  if (index !== lines.length || mcpHostname === landingHostname || firstOrigin !== secondOrigin) {
    throw new Error("The cloudflared configuration does not match the VSPiLink-managed format.");
  }
  if (credentialsPath) {
    if (!TUNNEL_NAME.test(tunnelValue)) throw new Error("The managed tunnel name is invalid.");
    return { tunnelName: tunnelValue, authKind: "origin-certificate", credentialsPath, mcpHostname, landingHostname, origin: firstOrigin };
  }
  if (!UUID.test(tunnelValue)) throw new Error("The managed tunnel identifier is invalid.");
  return {
    tunnelName: `vspilink-${tunnelValue.slice(0, 8)}`,
    authKind: "tunnel-token-file",
    tunnelId: tunnelValue.toLowerCase(),
    mcpHostname,
    landingHostname,
    origin: firstOrigin,
  };
}

function validateManagedUnits(options: {
  systemdUserDirectory: string;
  stateDirectory: string;
  configPath: string;
  cloudflaredConfigPath: string;
  serverUrl: string;
  origin: string;
  tunnelName: string;
  authKind: CloudflareAuthKind;
  tunnelId?: string;
  expectedUid?: number;
}): void {
  const server = readPrivateTextFile(path.join(options.systemdUserDirectory, SERVER_UNIT), options.expectedUid, 128 * 1024, "VSPiLink systemd unit");
  const tunnel = readPrivateTextFile(path.join(options.systemdUserDirectory, TUNNEL_UNIT), options.expectedUid, 128 * 1024, "cloudflared systemd unit");
  if (!server.startsWith(`${MANAGED_SYSTEMD_HEADER}\n`) || !tunnel.startsWith(`${MANAGED_SYSTEMD_HEADER}\n`)) {
    throw new Error("The existing systemd units are not managed by VSPiLink.");
  }
  const origin = new URL(options.origin);
  for (const required of [
    `Environment=${JSON.stringify(`PILINK_CONFIG=${path.resolve(options.configPath)}`)}`,
    `Environment=${JSON.stringify(`HOST=${origin.hostname}`)}`,
    `Environment=${JSON.stringify(`PORT=${origin.port}`)}`,
    `Environment=${JSON.stringify(`SERVER_URL=${options.serverUrl}`)}`,
  ]) {
    if (!server.split("\n").includes(required)) throw new Error("The VSPiLink systemd unit does not match the active private configuration.");
  }
  for (const required of [
    `Requires=${SERVER_UNIT}`,
    `ReadOnlyPaths=${JSON.stringify(options.stateDirectory)}`,
  ]) {
    if (!tunnel.split("\n").includes(required)) throw new Error("The cloudflared systemd unit does not match the managed configuration.");
  }
  const execLine = tunnel.split("\n").find((line) => line.startsWith("ExecStart="));
  if (!execLine || !execLine.includes(JSON.stringify(options.cloudflaredConfigPath))) {
    throw new Error("The cloudflared systemd unit does not use the expected managed configuration.");
  }
  if (options.authKind === "origin-certificate") {
    if (!execLine.endsWith(` ${JSON.stringify(options.tunnelName)}`) || execLine.includes('"--token-file"')) {
      throw new Error("The cloudflared systemd unit does not match the configured Named Tunnel.");
    }
  } else {
    const tokenMatch = execLine.match(/ "--token-file" ("(?:[^"\\]|\\.)+") ("(?:[^"\\]|\\.)+")$/);
    if (!tokenMatch || JSON.parse(tokenMatch[2]) !== options.tunnelId) {
      throw new Error("The cloudflared systemd unit does not match the configured token-based tunnel.");
    }
    const tokenPath = JSON.parse(tokenMatch[1]);
    if (typeof tokenPath !== "string" || !path.isAbsolute(tokenPath)) throw new Error("The managed tunnel token path is invalid.");
    assertPrivateFile(tokenPath, options.expectedUid, 64 * 1024, "token Cloudflare");
  }
}

function validateTunnelCredentials(filePath: string, expectedUid?: number): void {
  const contents = readPrivateTextFile(filePath, expectedUid, 64 * 1024, "managed tunnel credentials");
  try {
    const record = JSON.parse(contents) as Record<string, unknown>;
    const secret = typeof record.TunnelSecret === "string" ? Buffer.from(record.TunnelSecret, "base64") : Buffer.alloc(0);
    if (
      !record || Array.isArray(record) || typeof record.AccountTag !== "string" || !/^[a-f0-9]{16,128}$/i.test(record.AccountTag) ||
      typeof record.TunnelID !== "string" || !UUID.test(record.TunnelID) || secret.length < 16
    ) throw new Error();
  } catch {
    throw new Error("The managed tunnel credential file is invalid.");
  }
}

function assertPrivateDirectory(directory: string, expectedUid: number | undefined, label: string): void {
  let status: fs.Stats;
  try {
    status = fs.lstatSync(directory);
  } catch {
    throw new Error(`The ${label} is unavailable.`);
  }
  if (!status.isDirectory() || status.isSymbolicLink()) throw new Error(`The ${label} is not a real directory.`);
  if (expectedUid !== undefined && status.uid !== expectedUid) throw new Error(`The ${label} belongs to another user.`);
  if (process.platform !== "win32" && (status.mode & 0o077) !== 0) throw new Error(`The ${label} must have private 0700 permissions.`);
}

function assertPrivateFile(filePath: string, expectedUid: number | undefined, maxSize: number, label: string): fs.Stats {
  let status: fs.Stats;
  try {
    status = fs.lstatSync(filePath);
  } catch {
    throw new Error(`The ${label} file is unavailable.`);
  }
  if (!status.isFile() || status.isSymbolicLink() || status.nlink !== 1) throw new Error(`The ${label} file must be a regular file without links.`);
  if (status.size <= 0 || status.size > maxSize) throw new Error(`The ${label} file has an invalid size.`);
  if (expectedUid !== undefined && status.uid !== expectedUid) throw new Error(`The ${label} file belongs to another user.`);
  if (process.platform !== "win32" && (status.mode & 0o077) !== 0) throw new Error(`The ${label} file must be private (0600 permissions).`);
  return status;
}

function readPrivateTextFile(filePath: string, expectedUid: number | undefined, maxSize: number, label: string): string {
  const before = assertPrivateFile(filePath, expectedUid, maxSize, label);
  const contents = fs.readFileSync(filePath, "utf8");
  const after = fs.lstatSync(filePath);
  if (before.dev !== after.dev || before.ino !== after.ino || before.size !== after.size || before.mtimeMs !== after.mtimeMs) {
    throw new Error(`The ${label} file changed during verification.`);
  }
  return contents;
}

function strictHttpsOrigin(value: string): string {
  try {
    const parsed = new URL(value);
    if (parsed.protocol !== "https:" || parsed.username || parsed.password || parsed.port || parsed.search || parsed.hash || (parsed.pathname !== "/" && parsed.pathname !== "")) throw new Error();
    return parsed.origin;
  } catch {
    throw new Error("SERVER_URL must be an HTTPS origin without a path.");
  }
}

function strictHostname(value: unknown): string {
  if (typeof value !== "string") throw new Error("The managed tunnel hostname is missing.");
  const normalized = value.trim().toLowerCase().replace(/\.$/, "");
  if (normalized !== value.trim() || normalized.length > 253 || !normalized.split(".").every((label) => /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(label))) {
    throw new Error("Invalid managed tunnel hostname.");
  }
  return normalized;
}

function strictLoopbackOrigin(value: string): string {
  try {
    const parsed = new URL(value);
    if (
      parsed.protocol !== "http:" || parsed.hostname !== "127.0.0.1" || !parsed.port || parsed.username || parsed.password ||
      parsed.pathname !== "/" || parsed.search || parsed.hash
    ) throw new Error();
    return parsed.origin;
  } catch {
    throw new Error("The managed tunnel origin must use loopback HTTP.");
  }
}

function suggestedZone(first: string, second: string): string {
  const firstLabels = first.split(".");
  const secondLabels = second.split(".");
  const shared: string[] = [];
  while (firstLabels.length && secondLabels.length && firstLabels.at(-1) === secondLabels.at(-1)) {
    shared.unshift(firstLabels.pop() as string);
    secondLabels.pop();
  }
  if (shared.length < 2) throw new Error("Could not derive a common Cloudflare zone from the managed hostnames.");
  return shared.join(".");
}

function safeUnitState(output: string, fallback: string): string {
  const value = output.trim().toLowerCase();
  return /^[a-z][a-z0-9_.-]{0,79}$/.test(value) ? value : fallback;
}

function runStatusCommand(executable: string, args: readonly string[]): Promise<{ code: number | null; stdout: string }> {
  return runBoundedCommand(executable, args, 5_000);
}

function runManagedCommand(executable: string, args: readonly string[]): Promise<{ code: number | null; stdout: string }> {
  return runBoundedCommand(executable, args, 30_000);
}

function runBoundedCommand(executable: string, args: readonly string[], timeoutMs: number): Promise<{ code: number | null; stdout: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(executable, [...args], { shell: false, windowsHide: true, stdio: ["ignore", "pipe", "ignore"] });
    let stdout = "";
    let settled = false;
    const finish = (error?: Error, code: number | null = null) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      if (error) reject(error);
      else resolve({ code, stdout });
    };
    child.stdout.on("data", (chunk: Buffer) => {
      if (Buffer.byteLength(stdout) + chunk.length > 8_192) {
        child.kill("SIGKILL");
        finish(new Error("The systemd response is too large."));
        return;
      }
      stdout += chunk.toString("utf8");
    });
    child.once("error", () => finish(new Error("Could not query systemd.")));
    child.once("close", (code) => finish(undefined, code));
    const timeout = setTimeout(() => {
      child.kill("SIGKILL");
      finish(new Error("Timed out while checking systemd."));
    }, timeoutMs);
    timeout.unref();
  });
}
