#!/usr/bin/env node
import crypto from "node:crypto";
import dotenv from "dotenv";
import fs from "node:fs";
import path from "node:path";
import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import { pipeline } from "node:stream/promises";
import { Readable } from "node:stream";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import { loadEnvironment, loadRuntimeConfig, defaultConfigPath } from "./config.js";
import { loadClients, registerClient } from "./auth.js";

const [, , command = "start", ...args] = process.argv;
const configPath = process.env.PILINK_CONFIG || defaultConfigPath();
const MAX_DEFERRED_SERVER_OUTPUT = 64 * 1024;
let waitingForSetupCallback = false;
let deferredServerOutput = "";
let deferredServerOutputTruncated = false;

if (command === "init") {
  initialize();
} else if (command === "start") {
  void start(args.includes("--allow-unsafe-full-access"), args.includes("--setup"));
} else if (command === "serve") {
  startServer(args.includes("--allow-unsafe-full-access"));
} else if (command === "reset") {
  void reset(args);
} else {
  console.error("Usage: pilink <init|start|serve|reset> [--allow-unsafe-full-access] [--setup] [--yes] [--start]");
  process.exitCode = 1;
}

function initialize(): void {
  if (fs.existsSync(configPath)) {
    console.error(`Configuration already exists: ${configPath}`);
    return;
  }
  fs.mkdirSync(path.dirname(configPath), { recursive: true, mode: 0o700 });
  const workspace = process.cwd();
  const config = [
    "# Generated by pilink init. Keep this file private.",
    `PI_WORK_DIR=${workspace}`,
    `PI_DATA_DIR=${path.dirname(configPath)}`,
    "PORT=3200",
    `JWT_SECRET=${secret()}`,
    `PI_BOOTSTRAP_SECRET=${secret()}`,
    "PI_MAX_BASH_TIMEOUT=120",
    "# PI_UNSAFE_FULL_ACCESS=false",
    "# CORS_ORIGINS=https://chatgpt.com",
    "",
  ].join("\n");
  fs.writeFileSync(configPath, config, { mode: 0o600 });
  fs.chmodSync(configPath, 0o600);
  console.error(`Created private configuration: ${configPath}`);
  console.error("Use 'pilink start --allow-unsafe-full-access' only if you accept remote shell access to this machine.");
}

async function reset(args: string[]): Promise<void> {
  const targets = resetTargets();
  console.error("This deletes PiLink's generated configuration, OAuth clients, and managed Cloudflared binary.");
  console.error("It does not delete your repository or configured workspace.");
  console.error(`Targets:\n${targets.map((target) => `  - ${target}`).join("\n")}`);
  if (!args.includes("--yes")) {
    const readline = createInterface({ input: process.stdin, output: process.stderr });
    const confirmation = (await readline.question("Type RESET to continue: ")).trim();
    readline.close();
    if (confirmation !== "RESET") {
      console.error("Reset cancelled.");
      return;
    }
  }
  for (const target of targets) fs.rmSync(target, { recursive: true, force: true });
  console.error("PiLink state was reset. The next start is a first-time setup.");
  if (args.includes("--start")) {
    await start(args.includes("--allow-unsafe-full-access"), false);
  }
}

function resetTargets(): string[] {
  const configDirectory = path.dirname(configPath);
  let dataDirectory = configDirectory;
  if (fs.existsSync(configPath)) {
    const config = dotenv.parse(fs.readFileSync(configPath));
    if (config.PI_DATA_DIR) dataDirectory = path.resolve(config.PI_DATA_DIR);
  }
  const targets = new Set<string>([
    configPath,
    path.join(dataDirectory, "clients.json"),
    path.join(configDirectory, "bin", cloudflaredFileName()),
  ]);
  for (const target of targets) assertSafeResetTarget(target);
  return [...targets];
}

function assertSafeResetTarget(target: string): void {
  const resolved = path.resolve(target);
  if (resolved === path.parse(resolved).root || resolved === path.resolve(process.env.HOME || "")) {
    throw new Error(`Refusing to reset unsafe target: ${resolved}`);
  }
}

async function start(unsafe: boolean, forceSetup: boolean): Promise<void> {
  if (!fs.existsSync(configPath)) initialize();
  const port = readPort();
  let executable: string;
  try {
    executable = await ensureCloudflared();
  } catch (error) {
    console.error(error instanceof Error ? error.message : "Unable to install cloudflared");
    process.exitCode = 1;
    return;
  }
  const tunnel = spawn(executable, ["tunnel", "--url", `http://127.0.0.1:${port}`], { stdio: ["ignore", "pipe", "pipe"] });
  let server: ChildProcess | undefined;
  let shuttingDown = false;
  let output = "";
  const discoverUrl = (chunk: Buffer) => {
    output += chunk.toString();
    const url = output.match(/https:\/\/[-a-z0-9]+\.trycloudflare\.com/i)?.[0];
    if (url) {
      tunnel.stdout?.removeAllListeners("data");
      tunnel.stderr?.removeAllListeners("data");
      console.error(`Cloudflare Quick Tunnel: ${url}`);
      console.error(`Paste this MCP server URL in ChatGPT: ${url}/sse`);
      const { process: serverProc, ready } = startServer(unsafe, url, tunnel);
      server = serverProc;
      void ready.then(() => runFirstTimeSetup(url, forceSetup));
    }
  };
  tunnel.stdout?.on("data", discoverUrl);
  tunnel.stderr?.on("data", discoverUrl);
  tunnel.on("error", (error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") console.error("cloudflared could not be executed after installation.");
    else console.error(`Unable to start cloudflared: ${error.message}`);
    process.exitCode = 1;
  });
  tunnel.on("exit", (code) => {
    if (shuttingDown) return;
    shuttingDown = true;
    console.error(`cloudflared exited (${code ?? "signal"}); stopping PiLink.`);
    server?.kill("SIGINT");
    process.exitCode = code === 0 ? 0 : 1;
  });
}

async function runFirstTimeSetup(serverUrl: string, forceSetup: boolean): Promise<void> {
  try {
    loadEnvironment();
    loadRuntimeConfig();
    const clients = loadClients();
    if (!forceSetup && clients.length > 0) {
      console.error("An OAuth client is already configured. Use 'pilink start --setup' to register another client.");
      return;
    }
    printChatGptSetupInstructions(serverUrl);
    const readline = createInterface({ input: process.stdin, output: process.stderr });
    let callbackUrl: string;
    try {
      waitingForSetupCallback = true;
      console.error("\nPaste callback URL here:");
      callbackUrl = (await readline.question("> ")).trim();
    } finally {
      waitingForSetupCallback = false;
      readline.close();
      flushDeferredServerOutput();
    }
    if (!callbackUrl) {
      console.error("ChatGPT client registration skipped. Restart with 'pilink start --setup' when you have the callback URL.");
      return;
    }
    assertHttpUrl(callbackUrl, "callback URL");
    const { client, client_secret: clientSecret } = await registerClient(
      "ChatGPT",
      [callbackUrl],
      ["authorization_code"],
      "mcp:tools",
    );
    console.error("\nChatGPT OAuth client registered. Copy these values into ChatGPT now; the secret is shown only once.");
    console.error(`Client ID: ${client.client_id}`);
    console.error(`Client secret: ${clientSecret}`);
    console.error("Token endpoint auth method: client_secret_post");
    console.error(`Authorization URL: ${serverUrl}/oauth/authorize`);
    console.error(`Token URL: ${serverUrl}/oauth/token`);
    console.error("Scope: mcp:tools\n");
  } catch (error) {
    console.error(`First-time ChatGPT setup could not complete: ${error instanceof Error ? error.message : "unknown error"}`);
    console.error("The MCP server is still running. Restart with 'pilink start --setup' to try again.");
  }
}

function printChatGptSetupInstructions(serverUrl: string): void {
  console.error("\n=== First-time ChatGPT setup ===");
  console.error("1. In ChatGPT, open Settings → Apps/Connectors (or your MCP connections page) → Add connection.");
  console.error(`2. Set the connection/MCP server URL to: ${serverUrl}/sse`);
  console.error("3. Select Authentication: OAuth.");
  console.error("4. Open Advanced OAuth settings and select Registration method: User defined.");
  console.error("5. Copy ChatGPT's callback URL and paste it below. PiLink will create and print the client ID and secret.");
}

function assertHttpUrl(value: string, label: string): void {
  try {
    const url = new URL(value);
    if (url.protocol !== "http:" && url.protocol !== "https:") throw new Error();
  } catch {
    throw new Error(`The ${label} must be an absolute http(s) URL`);
  }
}

async function ensureCloudflared(): Promise<string> {
  const configuredPath = process.env.PI_CLOUDFLARED_PATH;
  if (configuredPath) {
    if (canRun(configuredPath)) return configuredPath;
    throw new Error(`PI_CLOUDFLARED_PATH is not executable: ${configuredPath}`);
  }
  if (canRun("cloudflared")) return "cloudflared";

  const destination = path.join(path.dirname(configPath), "bin", cloudflaredFileName());
  if (canRun(destination)) return destination;
  if (process.platform !== "linux") {
    throw new Error("cloudflared is not installed. Install it from https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/ and run pilink start again.");
  }

  const asset = cloudflaredAsset();
  console.error(`cloudflared is not installed; downloading the official ${asset} release for this first launch...`);
  const temporary = `${destination}.${process.pid}.tmp`;
  try {
    fs.mkdirSync(path.dirname(destination), { recursive: true, mode: 0o700 });
    const response = await fetch(`https://github.com/cloudflare/cloudflared/releases/latest/download/${asset}`, {
      redirect: "follow",
      signal: AbortSignal.timeout(120_000),
    });
    if (!response.ok || !response.body) throw new Error(`Cloudflare download failed (${response.status})`);
    await pipeline(Readable.fromWeb(response.body), fs.createWriteStream(temporary, { mode: 0o700 }));
    fs.chmodSync(temporary, 0o700);
    fs.renameSync(temporary, destination);
  } catch (error) {
    fs.rmSync(temporary, { force: true });
    throw new Error(`Could not install cloudflared automatically: ${error instanceof Error ? error.message : "unknown error"}`);
  }
  if (!canRun(destination)) {
    fs.rmSync(destination, { force: true });
    throw new Error("Downloaded cloudflared did not run successfully. Install it manually from https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/");
  }
  return destination;
}

function cloudflaredAsset(): string {
  const architecture = process.arch === "x64" ? "amd64" : process.arch === "arm64" ? "arm64" : undefined;
  if (!architecture) throw new Error(`Automatic cloudflared installation is unsupported for architecture '${process.arch}'. Install cloudflared manually.`);
  return `cloudflared-linux-${architecture}`;
}

function cloudflaredFileName(): string {
  return process.platform === "win32" ? "cloudflared.exe" : "cloudflared";
}

function canRun(executable: string): boolean {
  return spawnSync(executable, ["--version"], { stdio: "ignore" }).status === 0;
}

function startServer(unsafe: boolean, serverUrl?: string, tunnel?: ReturnType<typeof spawn>): { process: ChildProcess; ready: Promise<void> } {
  if (!fs.existsSync(configPath)) initialize();
  loadEnvironment();
  const config = loadRuntimeConfig();
  if (unsafe) console.error("DANGER: full-machine filesystem and shell access is enabled for every authorized MCP client.");
  const indexPath = path.join(path.dirname(fileURLToPath(import.meta.url)), "index.js");

  let resolveReady: () => void;
  const ready = new Promise<void>((resolve) => {
    resolveReady = resolve;
  });

  const timer = setTimeout(() => {
    resolveReady();
  }, 5000);

  const server = spawn(process.execPath, [indexPath], {
    env: {
      ...process.env,
      PILINK_CONFIG: configPath,
      HOST: "127.0.0.1",
      PI_DATA_DIR: config.dataDir,
      ...(serverUrl ? { SERVER_URL: serverUrl } : {}),
      ...(unsafe ? { PI_UNSAFE_FULL_ACCESS: "true" } : {}),
    },
    stdio: ["inherit", "inherit", "pipe"],
  });

  let stderrBuffer = "";
  server.stderr?.on("data", (chunk: Buffer) => {
    const text = chunk.toString();
    writeServerOutput(text);
    stderrBuffer += text;
    if (stderrBuffer.includes("╚══════════════════════════════════════════════════╝")) {
      clearTimeout(timer);
      resolveReady();
    }
  });

  const shutdown = () => {
    server.kill("SIGINT");
    tunnel?.kill("SIGTERM");
  };
  process.once("SIGINT", shutdown);
  process.once("SIGTERM", shutdown);
  server.on("exit", (code) => {
    clearTimeout(timer);
    resolveReady();
    tunnel?.kill("SIGTERM");
    process.exitCode = code ?? 1;
  });
  return { process: server, ready };
}

function writeServerOutput(output: string): void {
  if (waitingForSetupCallback) {
    const remaining = MAX_DEFERRED_SERVER_OUTPUT - deferredServerOutput.length;
    if (remaining > 0) deferredServerOutput += output.slice(0, remaining);
    if (output.length > remaining) deferredServerOutputTruncated = true;
  } else {
    process.stderr.write(output);
  }
}

function flushDeferredServerOutput(): void {
  if (deferredServerOutput) process.stderr.write(deferredServerOutput);
  if (deferredServerOutputTruncated) {
    process.stderr.write("[PiLink] Some server output was omitted while waiting for the callback URL.\n");
  }
  deferredServerOutput = "";
  deferredServerOutputTruncated = false;
}

function readPort(): number {
  if (!fs.existsSync(configPath)) return 3200;
  const match = fs.readFileSync(configPath, "utf8").match(/^PORT=(\d+)$/m);
  return match ? Number(match[1]) : 3200;
}

function secret(): string {
  return crypto.randomBytes(32).toString("base64url");
}
