#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import { pipeline } from "node:stream/promises";
import { Readable } from "node:stream";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import { loadEnvironment, loadRuntimeConfig, defaultConfigPath } from "./config.js";
import { loadClients, registerClient } from "./auth.js";

const [, , command = "start", ...args] = process.argv;
const configPath = process.env.PI_MCP_CONFIG || defaultConfigPath();

if (command === "init") {
  initialize();
} else if (command === "start") {
  void start(args.includes("--allow-unsafe-full-access"), args.includes("--setup"));
} else if (command === "serve") {
  startServer(args.includes("--allow-unsafe-full-access"));
} else {
  console.error("Usage: pi-mcp <init|start|serve> [--allow-unsafe-full-access] [--setup]");
  process.exitCode = 1;
}

function initialize(): void {
  if (fs.existsSync(configPath)) {
    console.error(`Configuration already exists: ${configPath}`);
    return;
  }
  fs.mkdirSync(path.dirname(configPath), { recursive: true, mode: 0o700 });
  const workspace = process.cwd();
  const config = [
    "# Generated by pi-mcp init. Keep this file private.",
    `PI_WORK_DIR=${workspace}`,
    `PI_DATA_DIR=${path.dirname(configPath)}`,
    "PORT=3200",
    `JWT_SECRET=${secret()}`,
    `PI_BOOTSTRAP_SECRET=${secret()}`,
    "PI_MAX_BASH_TIMEOUT=120",
    "# PI_UNSAFE_FULL_ACCESS=false",
    "# CORS_ORIGINS=https://chatgpt.com",
    "",
  ].join("\n");
  fs.writeFileSync(configPath, config, { mode: 0o600 });
  fs.chmodSync(configPath, 0o600);
  console.error(`Created private configuration: ${configPath}`);
  console.error("Use 'pi-mcp start --allow-unsafe-full-access' only if you accept remote shell access to this machine.");
}

async function start(unsafe: boolean, forceSetup: boolean): Promise<void> {
  if (!fs.existsSync(configPath)) initialize();
  const port = readPort();
  let executable: string;
  try {
    executable = await ensureCloudflared();
  } catch (error) {
    console.error(error instanceof Error ? error.message : "Unable to install cloudflared");
    process.exitCode = 1;
    return;
  }
  const tunnel = spawn(executable, ["tunnel", "--url", `http://127.0.0.1:${port}`], { stdio: ["ignore", "pipe", "pipe"] });
  let server: ChildProcess | undefined;
  let shuttingDown = false;
  let output = "";
  const discoverUrl = (chunk: Buffer) => {
    output += chunk.toString();
    const url = output.match(/https:\/\/[-a-z0-9]+\.trycloudflare\.com/i)?.[0];
    if (url) {
      tunnel.stdout?.removeAllListeners("data");
      tunnel.stderr?.removeAllListeners("data");
      console.error(`Cloudflare Quick Tunnel: ${url}`);
      console.error(`Paste this MCP server URL in ChatGPT: ${url}/sse`);
      server = startServer(unsafe, url, tunnel);
      void runFirstTimeSetup(url, forceSetup);
    }
  };
  tunnel.stdout?.on("data", discoverUrl);
  tunnel.stderr?.on("data", discoverUrl);
  tunnel.on("error", (error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") console.error("cloudflared could not be executed after installation.");
    else console.error(`Unable to start cloudflared: ${error.message}`);
    process.exitCode = 1;
  });
  tunnel.on("exit", (code) => {
    if (shuttingDown) return;
    shuttingDown = true;
    console.error(`cloudflared exited (${code ?? "signal"}); stopping PI-MCP.`);
    server?.kill("SIGINT");
    process.exitCode = code === 0 ? 0 : 1;
  });
}

async function runFirstTimeSetup(serverUrl: string, forceSetup: boolean): Promise<void> {
  try {
    loadEnvironment();
    loadRuntimeConfig();
    const clients = loadClients();
    if (!forceSetup && clients.length > 0) {
      console.error("An OAuth client is already configured. Use 'pi-mcp start --setup' to register another client.");
      return;
    }
    printChatGptSetupInstructions(serverUrl);
    const readline = createInterface({ input: process.stdin, output: process.stderr });
    const callbackUrl = (await readline.question("Paste the ChatGPT callback URL, then press Enter (leave blank to skip): ")).trim();
    readline.close();
    if (!callbackUrl) {
      console.error("ChatGPT client registration skipped. Restart with 'pi-mcp start --setup' when you have the callback URL.");
      return;
    }
    assertHttpUrl(callbackUrl, "callback URL");
    const { client, client_secret: clientSecret } = await registerClient(
      "ChatGPT",
      [callbackUrl],
      ["authorization_code"],
      "mcp:tools",
    );
    console.error("\nChatGPT OAuth client registered. Copy these values into ChatGPT now; the secret is shown only once.");
    console.error(`Client ID: ${client.client_id}`);
    console.error(`Client secret: ${clientSecret}`);
    console.error("Token endpoint auth method: client_secret_post");
    console.error(`Authorization URL: ${serverUrl}/oauth/authorize`);
    console.error(`Token URL: ${serverUrl}/oauth/token`);
    console.error("Scope: mcp:tools\n");
  } catch (error) {
    console.error(`First-time ChatGPT setup could not complete: ${error instanceof Error ? error.message : "unknown error"}`);
    console.error("The MCP server is still running. Restart with 'pi-mcp start --setup' to try again.");
  }
}

function printChatGptSetupInstructions(serverUrl: string): void {
  console.error("\n=== First-time ChatGPT setup ===");
  console.error("1. In ChatGPT, open Settings → Apps/Connectors (or your MCP connections page) → Add connection.");
  console.error(`2. Set the connection/MCP server URL to: ${serverUrl}/sse`);
  console.error("3. Select Authentication: OAuth.");
  console.error("4. Open Advanced OAuth settings and select Registration method: User defined.");
  console.error("5. Copy ChatGPT's callback URL and paste it below. PI-MCP will create and print the client ID and secret.");
}

function assertHttpUrl(value: string, label: string): void {
  try {
    const url = new URL(value);
    if (url.protocol !== "http:" && url.protocol !== "https:") throw new Error();
  } catch {
    throw new Error(`The ${label} must be an absolute http(s) URL`);
  }
}

async function ensureCloudflared(): Promise<string> {
  const configuredPath = process.env.PI_CLOUDFLARED_PATH;
  if (configuredPath) {
    if (canRun(configuredPath)) return configuredPath;
    throw new Error(`PI_CLOUDFLARED_PATH is not executable: ${configuredPath}`);
  }
  if (canRun("cloudflared")) return "cloudflared";

  const destination = path.join(path.dirname(configPath), "bin", cloudflaredFileName());
  if (canRun(destination)) return destination;
  if (process.platform !== "linux") {
    throw new Error("cloudflared is not installed. Install it from https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/ and run pi-mcp start again.");
  }

  const asset = cloudflaredAsset();
  console.error(`cloudflared is not installed; downloading the official ${asset} release for this first launch...`);
  const temporary = `${destination}.${process.pid}.tmp`;
  try {
    fs.mkdirSync(path.dirname(destination), { recursive: true, mode: 0o700 });
    const response = await fetch(`https://github.com/cloudflare/cloudflared/releases/latest/download/${asset}`, {
      redirect: "follow",
      signal: AbortSignal.timeout(120_000),
    });
    if (!response.ok || !response.body) throw new Error(`Cloudflare download failed (${response.status})`);
    await pipeline(Readable.fromWeb(response.body), fs.createWriteStream(temporary, { mode: 0o700 }));
    fs.chmodSync(temporary, 0o700);
    fs.renameSync(temporary, destination);
  } catch (error) {
    fs.rmSync(temporary, { force: true });
    throw new Error(`Could not install cloudflared automatically: ${error instanceof Error ? error.message : "unknown error"}`);
  }
  if (!canRun(destination)) {
    fs.rmSync(destination, { force: true });
    throw new Error("Downloaded cloudflared did not run successfully. Install it manually from https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/");
  }
  return destination;
}

function cloudflaredAsset(): string {
  const architecture = process.arch === "x64" ? "amd64" : process.arch === "arm64" ? "arm64" : undefined;
  if (!architecture) throw new Error(`Automatic cloudflared installation is unsupported for architecture '${process.arch}'. Install cloudflared manually.`);
  return `cloudflared-linux-${architecture}`;
}

function cloudflaredFileName(): string {
  return process.platform === "win32" ? "cloudflared.exe" : "cloudflared";
}

function canRun(executable: string): boolean {
  return spawnSync(executable, ["--version"], { stdio: "ignore" }).status === 0;
}

function startServer(unsafe: boolean, serverUrl?: string, tunnel?: ReturnType<typeof spawn>): ChildProcess {
  if (!fs.existsSync(configPath)) initialize();
  loadEnvironment();
  const config = loadRuntimeConfig();
  if (unsafe) console.error("DANGER: full-machine filesystem and shell access is enabled for every authorized MCP client.");
  const indexPath = path.join(path.dirname(fileURLToPath(import.meta.url)), "index.js");
  const server = spawn(process.execPath, [indexPath], {
    env: {
      ...process.env,
      PI_MCP_CONFIG: configPath,
      HOST: "127.0.0.1",
      PI_DATA_DIR: config.dataDir,
      ...(serverUrl ? { SERVER_URL: serverUrl } : {}),
      ...(unsafe ? { PI_UNSAFE_FULL_ACCESS: "true" } : {}),
    },
    stdio: "inherit",
  });
  const shutdown = () => {
    server.kill("SIGINT");
    tunnel?.kill("SIGTERM");
  };
  process.once("SIGINT", shutdown);
  process.once("SIGTERM", shutdown);
  server.on("exit", (code) => {
    tunnel?.kill("SIGTERM");
    process.exitCode = code ?? 1;
  });
  return server;
}

function readPort(): number {
  if (!fs.existsSync(configPath)) return 3200;
  const match = fs.readFileSync(configPath, "utf8").match(/^PORT=(\d+)$/m);
  return match ? Number(match[1]) : 3200;
}

function secret(): string {
  return crypto.randomBytes(32).toString("base64url");
}
