#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { defaultConfigPath } from "./config.js";

const [, , command = "start", ...args] = process.argv;
const configPath = process.env.PI_MCP_CONFIG || defaultConfigPath();

if (command === "init") {
  initialize();
} else if (command === "start") {
  start(args.includes("--allow-unsafe-full-access"));
} else if (command === "serve") {
  startServer(args.includes("--allow-unsafe-full-access"));
} else {
  console.error("Usage: pi-mcp <init|start|serve> [--allow-unsafe-full-access]");
  process.exitCode = 1;
}

function initialize(): void {
  if (fs.existsSync(configPath)) {
    console.error(`Configuration already exists: ${configPath}`);
    return;
  }
  fs.mkdirSync(path.dirname(configPath), { recursive: true, mode: 0o700 });
  const workspace = process.cwd();
  const config = [
    "# Generated by pi-mcp init. Keep this file private.",
    `PI_WORK_DIR=${workspace}`,
    `PI_DATA_DIR=${path.dirname(configPath)}`,
    "PORT=3200",
    `JWT_SECRET=${secret()}`,
    `PI_BOOTSTRAP_SECRET=${secret()}`,
    "PI_MAX_BASH_TIMEOUT=120",
    "# PI_UNSAFE_FULL_ACCESS=false",
    "# CORS_ORIGINS=https://chatgpt.com",
    "",
  ].join("\n");
  fs.writeFileSync(configPath, config, { mode: 0o600 });
  fs.chmodSync(configPath, 0o600);
  console.error(`Created private configuration: ${configPath}`);
  console.error("Use 'pi-mcp start --allow-unsafe-full-access' only if you accept remote shell access to this machine.");
}

function start(unsafe: boolean): void {
  if (!fs.existsSync(configPath)) initialize();
  const port = readPort();
  const tunnel = spawn("cloudflared", ["tunnel", "--url", `http://127.0.0.1:${port}`], { stdio: ["ignore", "pipe", "pipe"] });
  let output = "";
  const discoverUrl = (chunk: Buffer) => {
    output += chunk.toString();
    const url = output.match(/https:\/\/[-a-z0-9]+\.trycloudflare\.com/i)?.[0];
    if (url) {
      tunnel.stdout?.removeAllListeners("data");
      tunnel.stderr?.removeAllListeners("data");
      console.error(`Cloudflare Quick Tunnel: ${url}`);
      console.error("Configure this URL as the MCP server URL in ChatGPT.");
      startServer(unsafe, url, tunnel);
    }
  };
  tunnel.stdout?.on("data", discoverUrl);
  tunnel.stderr?.on("data", discoverUrl);
  tunnel.on("error", (error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") console.error("cloudflared is required. Install it from https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/");
    else console.error(`Unable to start cloudflared: ${error.message}`);
    process.exitCode = 1;
  });
  tunnel.on("exit", (code) => {
    if (!process.exitCode) console.error(`cloudflared exited (${code ?? "signal"})`);
    process.exitCode ||= 1;
  });
}

function startServer(unsafe: boolean, serverUrl?: string, tunnel?: ReturnType<typeof spawn>): void {
  if (!fs.existsSync(configPath)) initialize();
  if (unsafe) console.error("DANGER: full-machine filesystem and shell access is enabled for every authorized MCP client.");
  const indexPath = path.join(path.dirname(fileURLToPath(import.meta.url)), "index.js");
  const server = spawn(process.execPath, [indexPath], {
    env: {
      ...process.env,
      PI_MCP_CONFIG: configPath,
      HOST: "127.0.0.1",
      PI_DATA_DIR: path.dirname(configPath),
      ...(serverUrl ? { SERVER_URL: serverUrl } : {}),
      ...(unsafe ? { PI_UNSAFE_FULL_ACCESS: "true" } : {}),
    },
    stdio: "inherit",
  });
  const shutdown = () => {
    server.kill("SIGINT");
    tunnel?.kill("SIGTERM");
  };
  process.once("SIGINT", shutdown);
  process.once("SIGTERM", shutdown);
  server.on("exit", (code) => {
    tunnel?.kill("SIGTERM");
    process.exitCode = code ?? 1;
  });
}

function readPort(): number {
  if (!fs.existsSync(configPath)) return 3200;
  const match = fs.readFileSync(configPath, "utf8").match(/^PORT=(\d+)$/m);
  return match ? Number(match[1]) : 3200;
}

function secret(): string {
  return crypto.randomBytes(32).toString("base64url");
}
