import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

export type CliLinkStatus = "linked" | "already-linked" | "skipped" | "conflict";

export interface CliLinkResult {
  status: CliLinkStatus;
  linkPath?: string;
  reason?: string;
}

export interface CliLinkOptions {
  cliTarget?: string;
  homeDirectory?: string;
  pathValue?: string;
  nodeExecutable?: string;
  platform?: NodeJS.Platform;
  env?: NodeJS.ProcessEnv;
  info?: (message: string) => void;
  warn?: (message: string) => void;
}

const modulePath = fileURLToPath(import.meta.url);
const repositoryRoot = path.resolve(path.dirname(modulePath), "..");
const POSIX_LAUNCHER_MARKER = "# PILINK_GENERATED_SOURCE_LAUNCHER_V1";
const WINDOWS_LAUNCHER_MARKER = "@REM Generated by PiLink source build";

export function ensureCliLink(options: CliLinkOptions = {}): CliLinkResult {
  const env = options.env ?? process.env;
  const info = options.info ?? ((message: string) => console.log(message));
  const warn = options.warn ?? ((message: string) => console.warn(message));
  if (isTruthy(env.CI) || isTruthy(env.PILINK_SKIP_CLI_LINK)) {
    return { status: "skipped", reason: "disabled" };
  }

  const platform = options.platform ?? process.platform;
  const homeDirectory = path.resolve(options.homeDirectory ?? os.homedir());
  const pathValue = options.pathValue ?? env.PATH ?? "";
  const nodeExecutable = path.resolve(options.nodeExecutable ?? process.execPath);
  const cliTarget = path.resolve(options.cliTarget ?? path.join(repositoryRoot, "dist", "terminal-launcher.js"));
  if (!fs.existsSync(cliTarget)) {
    throw new Error(`PiLink CLI build output is missing: ${cliTarget}`);
  }

  const binDirectory = selectCliBinDirectory({
    pathValue,
    homeDirectory,
    nodeExecutable,
    platform,
  });
  if (!binDirectory) {
    warn("[PiLink] Build succeeded, but `pilink` was not added to PATH because no existing user-writable PATH directory was found.");
    warn("[PiLink] Run `npm run cli -- start` from this checkout, or add a user-owned bin directory to PATH and rebuild.");
    return { status: "skipped", reason: "no-safe-path-directory" };
  }

  if (platform === "win32") {
    return ensureWindowsShim(binDirectory, cliTarget, nodeExecutable, info, warn);
  }
  return ensurePosixLauncher(binDirectory, cliTarget, info, warn);
}

export function selectCliBinDirectory(options: {
  pathValue: string;
  homeDirectory: string;
  nodeExecutable: string;
  platform: NodeJS.Platform;
}): string | undefined {
  const pathEntries = options.pathValue
    .split(path.delimiter)
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => path.resolve(entry))
    .filter((entry) => !isNpmInjectedBin(entry, options.platform));
  const key = (value: string) => options.platform === "win32" ? value.toLowerCase() : value;
  const pathKeys = new Set(pathEntries.map(key));
  const preferred = [
    path.join(options.homeDirectory, ".local", "bin"),
    path.join(options.homeDirectory, "bin"),
    path.dirname(options.nodeExecutable),
  ].filter((candidate) => pathKeys.has(key(path.resolve(candidate))));

  let realHome: string;
  try {
    realHome = fs.realpathSync(options.homeDirectory);
  } catch {
    return undefined;
  }

  const seen = new Set<string>();
  for (const candidate of [...preferred, ...pathEntries]) {
    const resolved = path.resolve(candidate);
    const candidateKey = key(resolved);
    if (seen.has(candidateKey)) continue;
    seen.add(candidateKey);
    if (!isWithinHome(resolved, options.homeDirectory, options.platform)) continue;
    try {
      if (!fs.statSync(resolved).isDirectory()) continue;
      const realCandidate = fs.realpathSync(resolved);
      if (!isWithinHome(realCandidate, realHome, options.platform)) continue;
      fs.accessSync(resolved, fs.constants.W_OK);
      return resolved;
    } catch {
      continue;
    }
  }
  return undefined;
}

function ensurePosixLauncher(
  binDirectory: string,
  cliTarget: string,
  info: (message: string) => void,
  warn: (message: string) => void,
): CliLinkResult {
  fs.chmodSync(cliTarget, 0o755);
  const launcherPath = path.join(binDirectory, "pilink");
  const launcher = createPosixLauncher(cliTarget);

  if (fs.existsSync(launcherPath) || isDanglingSymlink(launcherPath)) {
    if (isOwnedPosixLauncher(launcherPath)) {
      const existing = fs.readFileSync(launcherPath, "utf8");
      if (existing === launcher) {
        fs.chmodSync(launcherPath, 0o700);
        info(`[PiLink] CLI already available: ${launcherPath}`);
        return { status: "already-linked", linkPath: launcherPath };
      }
      writePosixLauncher(launcherPath, launcher);
      info(`[PiLink] CLI launcher updated: ${launcherPath}`);
      return { status: "linked", linkPath: launcherPath };
    }

    if (isMigratablePiLinkSymlink(launcherPath, cliTarget)) {
      fs.unlinkSync(launcherPath);
      writePosixLauncher(launcherPath, launcher);
      info(`[PiLink] CLI launcher repaired: ${launcherPath}`);
      return { status: "linked", linkPath: launcherPath };
    }

    warn(`[PiLink] Build succeeded, but ${launcherPath} already exists and was not replaced.`);
    return { status: "conflict", linkPath: launcherPath, reason: "existing-command" };
  }

  writePosixLauncher(launcherPath, launcher);
  info(`[PiLink] CLI available as \`pilink\` via ${launcherPath}`);
  return { status: "linked", linkPath: launcherPath };
}

function createPosixLauncher(cliTarget: string): string {
  return `#!/bin/sh\n${POSIX_LAUNCHER_MARKER}\nexec ${quotePosixShellLiteral(cliTarget)} "$@"\n`;
}

function writePosixLauncher(launcherPath: string, content: string): void {
  fs.writeFileSync(launcherPath, content, { mode: 0o700 });
  fs.chmodSync(launcherPath, 0o700);
}

function isOwnedPosixLauncher(launcherPath: string): boolean {
  try {
    if (!fs.lstatSync(launcherPath).isFile()) return false;
    const prefix = `#!/bin/sh\n${POSIX_LAUNCHER_MARKER}\n`;
    return fs.readFileSync(launcherPath, "utf8").startsWith(prefix);
  } catch {
    return false;
  }
}

function isMigratablePiLinkSymlink(linkPath: string, cliTarget: string): boolean {
  if (path.basename(cliTarget) !== "terminal-launcher.js") return false;
  try {
    if (!fs.lstatSync(linkPath).isSymbolicLink()) return false;
    const rawTarget = fs.readlinkSync(linkPath);
    const resolvedRawTarget = path.resolve(path.dirname(linkPath), rawTarget);
    const previousTarget = path.join(path.dirname(cliTarget), "cli.js");
    if (resolvedRawTarget === path.resolve(cliTarget) || resolvedRawTarget === path.resolve(previousTarget)) {
      return true;
    }

    try {
      const currentTarget = fs.realpathSync(linkPath);
      if (currentTarget === fs.realpathSync(cliTarget)) return true;
      if (fs.existsSync(previousTarget) && currentTarget === fs.realpathSync(previousTarget)) return true;
    } catch {
      // A dangling symlink is migratable only when its raw target exactly
      // matches this checkout's current or previous PiLink launcher path.
    }
  } catch {
    return false;
  }
  return false;
}

function ensureWindowsShim(
  binDirectory: string,
  cliTarget: string,
  nodeExecutable: string,
  info: (message: string) => void,
  warn: (message: string) => void,
): CliLinkResult {
  const linkPath = path.join(binDirectory, "pilink.cmd");
  const marker = WINDOWS_LAUNCHER_MARKER;
  const shim = `${marker}\r\n@echo off\r\n"${escapeCmdLiteral(nodeExecutable)}" "${escapeCmdLiteral(cliTarget)}" %*\r\n`;
  if (fs.existsSync(linkPath)) {
    const existing = fs.readFileSync(linkPath, "utf8");
    if (!existing.startsWith(marker)) {
      warn(`[PiLink] Build succeeded, but ${linkPath} already exists and was not replaced.`);
      return { status: "conflict", linkPath, reason: "existing-command" };
    }
    if (existing === shim) {
      info(`[PiLink] CLI already available: ${linkPath}`);
      return { status: "already-linked", linkPath };
    }
  }
  fs.writeFileSync(linkPath, shim, { mode: 0o700 });
  info(`[PiLink] CLI available as \`pilink\` via ${linkPath}`);
  return { status: "linked", linkPath };
}

function isWithinHome(candidate: string, homeDirectory: string, platform: NodeJS.Platform): boolean {
  const normalize = (value: string) => platform === "win32" ? value.toLowerCase() : value;
  const relative = path.relative(normalize(path.resolve(homeDirectory)), normalize(path.resolve(candidate)));
  return relative !== "" && relative !== ".." && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative);
}

function isNpmInjectedBin(candidate: string, platform: NodeJS.Platform): boolean {
  const normalized = candidate.replaceAll("\\", "/");
  const comparable = platform === "win32" ? normalized.toLowerCase() : normalized;
  return comparable.endsWith("/node_modules/.bin") || comparable.includes("/node_modules/.bin/");
}

function isDanglingSymlink(targetPath: string): boolean {
  try {
    return fs.lstatSync(targetPath).isSymbolicLink();
  } catch {
    return false;
  }
}

function quotePosixShellLiteral(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

function escapeCmdLiteral(value: string): string {
  return value.replaceAll("%", "%%").replaceAll('"', '""');
}

function isTruthy(value: string | undefined): boolean {
  return /^(?:1|true|yes|on)$/iu.test(value ?? "");
}

if (process.argv[1] && path.resolve(process.argv[1]) === modulePath) {
  try {
    ensureCliLink();
  } catch (error) {
    console.error(`[PiLink] Unable to expose the CLI: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  }
}
